# Generated by Django 3.2.9 on 2022-03-23 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='photo_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
