# Generated by Django 3.2.9 on 2022-04-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersgroup_photo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersgroupimages',
            name='user_group',
        ),
        migrations.DeleteModel(
            name='UsersGroup',
        ),
        migrations.DeleteModel(
            name='UsersGroupImages',
        ),
    ]
