# Generated by Django 3.2.9 on 2022-04-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='owner',
            field=models.CharField(default='kraszor', editable=False, max_length=100),
        ),
    ]
