# Generated by Django 3.2.9 on 2022-05-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_usersgroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='owner',
            field=models.CharField(default=None, editable=False, max_length=100),
        ),
    ]
