# Generated by Django 3.2.9 on 2022-05-12 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0009_alter_usersgroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
