# Generated by Django 3.2.9 on 2022-05-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0010_alter_usersgroup_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('resolution_width', models.IntegerField()),
                ('resolution_height', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
                ('longitude', models.DecimalField(decimal_places=2, default=None, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=300)),
                ('date_taken', models.DateTimeField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.usersgroup')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.image')),
                ('place', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='photo.place')),
            ],
        ),
    ]
