# Generated by Django 3.2.9 on 2022-05-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0012_auto_20220513_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersgroup',
            name='color_group',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='photo_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersgroup',
            name='tags',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
