# Generated by Django 3.2.9 on 2022-05-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0014_auto_20220513_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='color_group',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='tags',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
