# Generated by Django 3.2.9 on 2022-05-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0015_auto_20220513_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
