# Generated by Django 3.2.9 on 2022-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0016_auto_20220513_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='size',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
