# Generated by Django 3.2.9 on 2022-05-15 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo', '0020_alter_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='owner',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='photo_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
