# Generated by Django 3.2.9 on 2022-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0021_auto_20220515_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='color_group',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Red', 'Red'), ('Aqua', 'Aqua'), ('DarkBlue', 'DarkBlue'), ('Generic', 'Generic'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Violet', 'Violet'), ('Yellow', 'Yellow')], default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='is_local',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='tags',
            field=models.CharField(default='#none', max_length=200),
        ),
    ]
