# Generated by Django 3.2.9 on 2022-05-17 00:29

from django.db import migrations, models
import photo.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0022_auto_20220517_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='tags',
            field=models.CharField(default='#none', max_length=200, validators=[photo.validators.validate_hashtags]),
        ),
    ]
