# Generated by Django 3.2.9 on 2022-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0023_alter_usersgroup_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='edit_time',
            field=models.DateField(auto_now=True),
        ),
    ]
