# Generated by Django 3.2.9 on 2022-05-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0024_auto_20220522_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersgroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usersgroup',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
